### ISSUE TITLE
ImportError: No module named core

### ISSUE THREAD

**Issue by bmh1980** [Abstrys/rst2db#1]
After installing rst2db via pip if I try to start it, I get the following traceback.

$ rst2db --help
Traceback (most recent call last):
  File "/usr/local/bin/rst2db", line 9, in <module>
    load_entry_point('rst2db==1.0', 'console_scripts', 'rst2db')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2318, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/abstrys/cmd_rst2db.py", line 14, in <module>
    from docutils.core import publish_string
ImportError: No module named core

If I do this import from the command line, it works.

$ python -c 'from docutils.core import publish_string'
$

**Comment by EronHennessey** [comment]
Thanks so much, I'll look into this. What OS/Python variant are you running (meaning: what are the results of `python --version`)?

**Comment by bmh1980** [comment]
I’m using Python 2.7.9 on Ubuntu 15.04.

**Comment by Aleksei-Badyaev** [comment]
I already fix this error in my fork of repo and sent pull request to Eron!

**Comment by EronHennessey** [comment]
Thank you Aleksei!  I'll pull this into the main repo. Sorry about the wait!

**Comment by EronHennessey** [comment]
PR merged. Thanks again!
